name: Sync to Hugging Face hub
on:
  push:
    branches: [main]
  workflow_dispatch:
jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
      - name: Set up git remote
        run: |
          git config user.name "edaUsha"
          git config user.email "edaUsha@users.noreply.github.com"
          git remote add hub https://edaUsha:${{ secrets.HF_TOKEN }}@huggingface.co/spaces/edaUsha/Pose-Based-Swimming-Stroke-Detection
      - name: Push to hub
        run: |
          git pull hub main --rebase
          git push hub main
